import type { Centre, TrialSlot, Subject, Level } from '@/types/database'

// ── Lookup data ───────────────────────────────────────────────

export const MOCK_SUBJECTS: Subject[] = [
  { id: 'subj-math', name: 'Mathematics', sort_order: 1, is_custom: false, created_at: '2026-01-01T00:00:00Z' },
  { id: 'subj-eng', name: 'English Language', sort_order: 2, is_custom: false, created_at: '2026-01-01T00:00:00Z' },
  { id: 'subj-sci', name: 'Science', sort_order: 3, is_custom: false, created_at: '2026-01-01T00:00:00Z' },
  { id: 'subj-chi', name: 'Chinese Language', sort_order: 4, is_custom: false, created_at: '2026-01-01T00:00:00Z' },
]

export const MOCK_LEVELS: Level[] = [
  { id: 'lvl-p1', code: 'P1', label: 'Primary 1', level_group: 'primary', sort_order: 1, created_at: '2026-01-01T00:00:00Z' },
  { id: 'lvl-p2', code: 'P2', label: 'Primary 2', level_group: 'primary', sort_order: 2, created_at: '2026-01-01T00:00:00Z' },
  { id: 'lvl-p3', code: 'P3', label: 'Primary 3', level_group: 'primary', sort_order: 3, created_at: '2026-01-01T00:00:00Z' },
  { id: 'lvl-p4', code: 'P4', label: 'Primary 4', level_group: 'primary', sort_order: 4, created_at: '2026-01-01T00:00:00Z' },
  { id: 'lvl-p5', code: 'P5', label: 'Primary 5', level_group: 'primary', sort_order: 5, created_at: '2026-01-01T00:00:00Z' },
  { id: 'lvl-p6', code: 'P6', label: 'Primary 6', level_group: 'primary', sort_order: 6, created_at: '2026-01-01T00:00:00Z' },
  { id: 'lvl-s1', code: 'SEC1', label: 'Secondary 1', level_group: 'secondary', sort_order: 7, created_at: '2026-01-01T00:00:00Z' },
  { id: 'lvl-s2', code: 'SEC2', label: 'Secondary 2', level_group: 'secondary', sort_order: 8, created_at: '2026-01-01T00:00:00Z' },
  { id: 'lvl-s3', code: 'SEC3', label: 'Secondary 3', level_group: 'secondary', sort_order: 9, created_at: '2026-01-01T00:00:00Z' },
  { id: 'lvl-s4', code: 'SEC4', label: 'Secondary 4', level_group: 'secondary', sort_order: 10, created_at: '2026-01-01T00:00:00Z' },
]

// ── Centres ───────────────────────────────────────────────────

export const MOCK_CENTRES: Centre[] = [
  {
    id: 'centre-1',
    name: 'Bright Minds Tuition',
    slug: 'bright-minds-tuition',
    area: 'Buona Vista',
    address: '71 Buona Vista Drive, #02-18, Singapore 138951',
    description:
      'Bright Minds has been helping primary school students master Mathematics and Science since 2014. Our small-group sessions allow every child to ask questions freely and progress at the right pace.',
    teaching_style:
      'Concept-first, then application. We never teach to the test — we build understanding that holds up under exam pressure. Sessions use a mix of worked examples, guided practice, and independent problem sets.',
    teacher_bio:
      'Ms Rachel Tan has 12 years of teaching experience, having taught at a top primary school before founding Bright Minds. She holds a Bachelor of Science (Mathematics) from NUS.',
    teacher_qualifications: 'B.Sc Mathematics (NUS), former MOE teacher (12 years)',
    class_size: 6,
    replacement_class_policy:
      'One replacement class per term with 48 hours advance notice. Replacement classes are scheduled on weekday evenings.',
    makeup_class_policy: 'Makeup classes available subject to availability. No makeup for no-shows without prior notice.',
    commitment_terms: 'Month-to-month. No lock-in contract.',
    notice_period_terms: '2 weeks written notice to withdraw.',
    payment_terms: 'Monthly in advance by the 1st of each month via PayNow.',
    other_policies: null,
    parking_info: 'Free parking available at the building carpark.',
    nearest_mrt: 'Buona Vista MRT (EW21/CC22), 5-minute walk',
    years_operating: 12,
    track_record: 'Over 200 students placed in top secondary schools. 90% of P6 students score AL1 or AL2 in Mathematics.',
    contact_email: null,
    image_urls: [],
    trial_type: 'free',
    paynow_qr_image_url: null,
    is_active: true,
    is_paused: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'centre-2',
    name: 'The English Room',
    slug: 'the-english-room',
    area: 'Tampines',
    address: '4 Tampines Central 5, #03-22 Tampines Mall, Singapore 529510',
    description:
      'The English Room specialises in English Language and Creative Writing for primary and lower secondary students. We believe in building confident communicators, not just exam-ready students.',
    teaching_style:
      'Discussion-based, writing-intensive. Every session includes a short writing component. We focus on idea generation, structure, and precise vocabulary — skills that transfer across all subjects.',
    teacher_bio:
      'Mr Darren Lim was an English teacher at a Gifted Education Programme school for 8 years. He founded The English Room in 2019 to bring GEP-style thinking to mainstream students.',
    teacher_qualifications: 'B.A. English Literature (NTU), GEP-trained educator (8 years)',
    class_size: 8,
    replacement_class_policy:
      'Replacement classes offered within the same month with 24 hours notice. Subject to availability.',
    makeup_class_policy: 'No makeup classes. Recordings of missed sessions available upon request.',
    commitment_terms: 'Minimum 3-month commitment after the trial class.',
    notice_period_terms: '1 month written notice to withdraw after the minimum commitment period.',
    payment_terms: 'Termly (3 months) in advance. GIRO available.',
    other_policies: null,
    parking_info: 'Tampines Mall carpark — first 2 hours free with validation.',
    nearest_mrt: 'Tampines MRT (EW2/DT32), direct mall connection',
    years_operating: 7,
    track_record: 'Students consistently score A1/A2 in PSLE English. Several students have won national creative writing competitions.',
    contact_email: null,
    image_urls: [],
    trial_type: 'free',
    paynow_qr_image_url: null,
    is_active: true,
    is_paused: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
]

// ── Trial slots ───────────────────────────────────────────────

export const MOCK_SLOTS: (TrialSlot & {
  subject: Subject
  level: Level
  centre: Centre
})[] = [
  // Bright Minds — Mathematics
  {
    id: 'slot-1',
    centre_id: 'centre-1',
    subject_id: 'subj-math',
    level_id: 'lvl-p5',
    date: '2026-03-14',
    start_time: '10:00:00',
    end_time: '11:30:00',
    trial_fee: 45,
    max_students: 2,
    spots_remaining: 2,
    age_min: null,
    age_max: null,
    custom_level: null,
    notes: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    subject: { id: 'subj-math', name: 'Mathematics', sort_order: 1, is_custom: false, created_at: '' },
    level: { id: 'lvl-p5', code: 'P5', label: 'Primary 5', level_group: 'primary', sort_order: 5, created_at: '' },
    centre: MOCK_CENTRES[0],
  },
  {
    id: 'slot-2',
    centre_id: 'centre-1',
    subject_id: 'subj-math',
    level_id: 'lvl-p6',
    date: '2026-03-14',
    start_time: '13:00:00',
    end_time: '14:30:00',
    trial_fee: 50,
    max_students: 2,
    spots_remaining: 1,
    age_min: null,
    age_max: null,
    custom_level: null,
    notes: 'PSLE preparation focus',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    subject: { id: 'subj-math', name: 'Mathematics', sort_order: 1, is_custom: false, created_at: '' },
    level: { id: 'lvl-p6', code: 'P6', label: 'Primary 6', level_group: 'primary', sort_order: 6, created_at: '' },
    centre: MOCK_CENTRES[0],
  },
  {
    id: 'slot-3',
    centre_id: 'centre-1',
    subject_id: 'subj-sci',
    level_id: 'lvl-p4',
    date: '2026-03-15',
    start_time: '10:00:00',
    end_time: '11:00:00',
    trial_fee: 40,
    max_students: 3,
    spots_remaining: 3,
    age_min: null,
    age_max: null,
    custom_level: null,
    notes: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    subject: { id: 'subj-sci', name: 'Science', sort_order: 3, is_custom: false, created_at: '' },
    level: { id: 'lvl-p4', code: 'P4', label: 'Primary 4', level_group: 'primary', sort_order: 4, created_at: '' },
    centre: MOCK_CENTRES[0],
  },
  {
    id: 'slot-4',
    centre_id: 'centre-1',
    subject_id: 'subj-math',
    level_id: 'lvl-p3',
    date: '2026-03-21',
    start_time: '10:00:00',
    end_time: '11:00:00',
    trial_fee: 40,
    max_students: 3,
    spots_remaining: 3,
    age_min: null,
    age_max: null,
    custom_level: null,
    notes: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    subject: { id: 'subj-math', name: 'Mathematics', sort_order: 1, is_custom: false, created_at: '' },
    level: { id: 'lvl-p3', code: 'P3', label: 'Primary 3', level_group: 'primary', sort_order: 3, created_at: '' },
    centre: MOCK_CENTRES[0],
  },
  // The English Room — English
  {
    id: 'slot-5',
    centre_id: 'centre-2',
    subject_id: 'subj-eng',
    level_id: 'lvl-p5',
    date: '2026-03-15',
    start_time: '09:00:00',
    end_time: '10:30:00',
    trial_fee: 50,
    max_students: 2,
    spots_remaining: 2,
    age_min: null,
    age_max: null,
    custom_level: null,
    notes: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    subject: { id: 'subj-eng', name: 'English Language', sort_order: 2, is_custom: false, created_at: '' },
    level: { id: 'lvl-p5', code: 'P5', label: 'Primary 5', level_group: 'primary', sort_order: 5, created_at: '' },
    centre: MOCK_CENTRES[1],
  },
  {
    id: 'slot-6',
    centre_id: 'centre-2',
    subject_id: 'subj-eng',
    level_id: 'lvl-p6',
    date: '2026-03-15',
    start_time: '11:00:00',
    end_time: '12:30:00',
    trial_fee: 55,
    max_students: 2,
    spots_remaining: 2,
    age_min: null,
    age_max: null,
    custom_level: null,
    notes: 'PSLE oral + composition focus',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    subject: { id: 'subj-eng', name: 'English Language', sort_order: 2, is_custom: false, created_at: '' },
    level: { id: 'lvl-p6', code: 'P6', label: 'Primary 6', level_group: 'primary', sort_order: 6, created_at: '' },
    centre: MOCK_CENTRES[1],
  },
  {
    id: 'slot-7',
    centre_id: 'centre-2',
    subject_id: 'subj-eng',
    level_id: 'lvl-s1',
    date: '2026-03-22',
    start_time: '14:00:00',
    end_time: '15:30:00',
    trial_fee: 55,
    max_students: 3,
    spots_remaining: 3,
    age_min: null,
    age_max: null,
    custom_level: null,
    notes: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    subject: { id: 'subj-eng', name: 'English Language', sort_order: 2, is_custom: false, created_at: '' },
    level: { id: 'lvl-s1', code: 'SEC1', label: 'Secondary 1', level_group: 'secondary', sort_order: 7, created_at: '' },
    centre: MOCK_CENTRES[1],
  },
]
